name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          changelog: |
            ## {{ package }} {{ version }}
            
            {% if custom %}
            {{ custom }}
            {% endif %}
            
            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}